[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_limit = "8000000" 
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
